import Head from 'next/head'



// import Search from '../components/Search'
import Search from '../components/Search/Search'
import { useEffect, useState } from 'react'



export default function Home() {

    const [desas,setDesas] = useState([])
    useEffect(async()=>{
        const res = await fetch('/api/desas')
        const desa = await res.json()
        setDesas(desa)
    },[])
    
        return (
            
            <div  className="">
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                {/* <Headers/> */}
                   
                    <Search desas={desas} />
                    
            </div>
           
        )
    } 
    
